



INSERT INTO matchs (saison_id, date_du_match, numero_match, equipedom_id, equipevisit_id,qt1_dom,qt2_dom,qt3_dom,qt4_dom,qt1_visit,qt2_visit,qt3_visit,qt4_visit,arbitre1,coach_dom,coach_visit,comite_id)
VALUES ((SELECT id_saison FROM saison WHERE annee=18),'2018-03-24',003096,(SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))),(SELECT id_equipes FROM equipes WHERE (nom_equipe='ABC_LUTTERBACH' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))),18,18,13,28,4,14,13,4,'BOURQUARD E.','SIMON E','MEHR F',(SELECT id_comite FROM comite WHERE nom_comite='LR02'));

UPDATE matchs SET arbitre2 =' CARLADOUS T.' WHERE ((numero_match=003096) AND (comite_id = (SELECT id_comite FROM comite WHERE nom_comite= 'LR02')) AND (saison_id = (SELECT id_saison FROM saison WHERE annee=18)));


INSERT INTO jointure_joueurs_equipes (joueurs_id,equipes_id)
VALUES ((SELECT id_joueurs FROM joueurs WHERE (nom_joueur='DESLOGES_GAUVAIN' AND licence='VT030233')),(SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite= 'LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))));


INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='PAUL_ROMAIN' AND licence='VT030225')),(SELECT id_saison FROM saison WHERE annee=18),NULL,8,2,2,0,0,2,2,2,0,NULL,NULL,true,4);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='GROTZINGER_GUILLAUME' AND licence='VT040421')),(SELECT id_saison FROM saison WHERE annee=18),NULL,13,6,0,0,6,1,2,0,0,NULL,NULL,true,5);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='BISKUPSKI_NOAH' AND licence='VT040702')),(SELECT id_saison FROM saison WHERE annee=18),NULL,16,8,0,0,8,0,0,1,0,NULL,NULL,true,6);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='SCHOENACKER_MATTEO' AND licence='VT040483')),(SELECT id_saison FROM saison WHERE annee=18),NULL,11,4,0,1,3,3,4,0,0,NULL,NULL,true,7);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='POUGARY_ETHAN' AND licence='VT040481')),(SELECT id_saison FROM saison WHERE annee=18),NULL,10,5,0,1,4,0,0,2,0,NULL,NULL,false,9);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='BERTRAND_NOE' AND licence='VT040400')),(SELECT id_saison FROM saison WHERE annee=18),NULL,2,1,0,1,0,0,4,0,0,NULL,NULL,true,10);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='DESLOGES_GAUVAIN' AND licence='VT030233')),(SELECT id_saison FROM saison WHERE annee=18),NULL,5,2,1,0,1,0,0,1,0,NULL,NULL,false,11);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='MAILLARD_SWAN' AND licence='VT046271')),(SELECT id_saison FROM saison WHERE annee=18),NULL,6,3,0,1,2,0,0,0,0,NULL,NULL,false,12);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='STEFFEN_CHRISTOPHE' AND licence='VT030177')),(SELECT id_saison FROM saison WHERE annee=18),NULL,6,3,0,0,3,0,0,0,0,NULL,NULL,false,13);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='SPONY_ROMAIN' AND licence='VT040381')),(SELECT id_saison FROM saison WHERE annee=18),NULL,5,2,1,1,0,0,0,2,2,NULL,NULL,true,5);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='ROMAIL_KEVIN' AND licence='VT040802')),(SELECT id_saison FROM saison WHERE annee=18),NULL,4,2,0,1,1,0,0,3,4,NULL,NULL,true,6);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='PELZ_NICOLAS' AND licence='VT040804')),(SELECT id_saison FROM saison WHERE annee=18),NULL,7,3,1,1,1,0,0,1,0,NULL,NULL,true,7);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='BERTHOD_HUGO' AND licence='VT048542')),(SELECT id_saison FROM saison WHERE annee=18),NULL,2,1,0,0,1,0,0,1,2,NULL,NULL,false,8);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='CREDOZ_MARTIN' AND licence='VT040850')),(SELECT id_saison FROM saison WHERE annee=18),NULL,9,4,1,1,2,0,0,2,0,NULL,NULL,true,9);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='LEROUGE_FLORENT' AND licence='VT040427')),(SELECT id_saison FROM saison WHERE annee=18),NULL,2,1,0,0,1,0,0,0,0,NULL,NULL,false,10);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='DE_JOANNIS_DE_VERCLOS_MERLIN' AND licence='VT049889')),(SELECT id_saison FROM saison WHERE annee=18),NULL,6,3,0,1,2,0,0,4,4,NULL,NULL,true,12);


INSERT INTO stats_equipes (matchs_id,equipes_id,saison_id,ptsm,ptse,pts5,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,fautesprov)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18))),(SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))),(SELECT id_saison FROM saison WHERE annee=18),77,35,50,34,3,4,27,6,12,6,0,13);

INSERT INTO stats_equipes (matchs_id,equipes_id,saison_id,ptsm,ptse,pts5,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,fautesprov)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18))),(SELECT id_equipes FROM equipes WHERE (nom_equipe='ABC_LUTTERBACH' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))),(SELECT id_saison FROM saison WHERE annee=18),35,77,31,16,3,5,8,0,0,13,12,6);

UPDATE stats_equipes SET age=13.3333,antisportive=0,technique=0,disqualifiante=0 WHERE (matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18))) AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))));

UPDATE stats_equipes SET age=13,antisportive=0,technique=0,disqualifiante=0 WHERE (matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=003096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18))) AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ABC_LUTTERBACH' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))));


INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=3096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT040400' AND nom_joueur='BERTRAND_NOE'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040702' AND nom_joueur='BISKUPSKI_NOAH'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040421' AND nom_joueur='GROTZINGER_GUILLAUME'),(SELECT id_joueurs FROM joueurs WHERE licence='VT030225' AND nom_joueur='PAUL_ROMAIN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040483' AND nom_joueur='SCHOENACKER_MATTEO'),NULL,36,18);
INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=3096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT040400' AND nom_joueur='BERTRAND_NOE'),(SELECT id_joueurs FROM joueurs WHERE licence='VT030233' AND nom_joueur='DESLOGES_GAUVAIN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT046271' AND nom_joueur='MAILLARD_SWAN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040481' AND nom_joueur='POUGARY_ETHAN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT030177' AND nom_joueur='STEFFEN_CHRISTOPHE'),NULL,0,0);
INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=3096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT040702' AND nom_joueur='BISKUPSKI_NOAH'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040421' AND nom_joueur='GROTZINGER_GUILLAUME'),(SELECT id_joueurs FROM joueurs WHERE licence='VT046271' AND nom_joueur='MAILLARD_SWAN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT030225' AND nom_joueur='PAUL_ROMAIN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040481' AND nom_joueur='POUGARY_ETHAN'),NULL,41,17);
INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ABC_LUTTERBACH' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=3096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT040850' AND nom_joueur='CREDOZ_MARTIN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT049889' AND nom_joueur='DE_JOANNIS_DE_VERCLOS_MERLIN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040804' AND nom_joueur='PELZ_NICOLAS'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040802' AND nom_joueur='ROMAIL_KEVIN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040381' AND nom_joueur='SPONY_ROMAIN'),NULL,35,77);
INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ABC_LUTTERBACH' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U15M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=3096 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U15M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT048542' AND nom_joueur='BERTHOD_HUGO'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040850' AND nom_joueur='CREDOZ_MARTIN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT049889' AND nom_joueur='DE_JOANNIS_DE_VERCLOS_MERLIN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040427' AND nom_joueur='LEROUGE_FLORENT'),(SELECT id_joueurs FROM joueurs WHERE licence='VT040804' AND nom_joueur='PELZ_NICOLAS'),NULL,0,0);




INSERT INTO matchs (saison_id, date_du_match, numero_match, equipedom_id, equipevisit_id,qt1_dom,qt2_dom,qt3_dom,qt4_dom,qt1_visit,qt2_visit,qt3_visit,qt4_visit,arbitre1,coach_dom,coach_visit,comite_id)
VALUES ((SELECT id_saison FROM saison WHERE annee=18),'2018-03-24',002097,(SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))),(SELECT id_equipes FROM equipes WHERE (nom_equipe='DUTTLENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))),15,10,14,17,29,18,21,12,'BOURQUARD E.','SIMON E','LECLUSE V',(SELECT id_comite FROM comite WHERE nom_comite='LR02'));

UPDATE matchs SET arbitre2 =' CARLADOUS T.' WHERE ((numero_match=002097) AND (comite_id = (SELECT id_comite FROM comite WHERE nom_comite= 'LR02')) AND (saison_id = (SELECT id_saison FROM saison WHERE annee=18)));


INSERT INTO joueurs (licence, nom_joueur, nom_joueur_raccourci, adn)
VALUES ('VT013231','REBHUN_FLORENT','REBHUN_F',2001);

INSERT INTO jointure_joueurs_equipes (joueurs_id,equipes_id)
VALUES ((SELECT id_joueurs FROM joueurs WHERE (nom_joueur='REBHUN_FLORENT' AND licence='VT013231')),(SELECT id_equipes FROM equipes WHERE (nom_equipe='DUTTLENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite= 'LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))));

INSERT INTO jointure_joueurs_equipes (joueurs_id,equipes_id)
VALUES ((SELECT id_joueurs FROM joueurs WHERE (nom_joueur='DEL_PIN_JULES_VICTOR' AND licence='VT020796')),(SELECT id_equipes FROM equipes WHERE (nom_equipe='DUTTLENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite= 'LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))));

INSERT INTO joueurs (licence, nom_joueur, nom_joueur_raccourci, adn)
VALUES ('VT013646','HANS_QUENTIN','HANS_Q',2001);

INSERT INTO jointure_joueurs_equipes (joueurs_id,equipes_id)
VALUES ((SELECT id_joueurs FROM joueurs WHERE (nom_joueur='HANS_QUENTIN' AND licence='VT013646')),(SELECT id_equipes FROM equipes WHERE (nom_equipe='DUTTLENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite= 'LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))));


INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='LIBMAN_ROBIN' AND licence='VT020166')),(SELECT id_saison FROM saison WHERE annee=18),NULL,0,0,0,0,0,0,0,4,8,NULL,NULL,false,4);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='STATH_THIBAUT' AND licence='VT010201')),(SELECT id_saison FROM saison WHERE annee=18),NULL,14,5,2,1,2,2,3,3,0,NULL,NULL,true,5);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='CHAMASSI_UGO' AND licence='VT020046')),(SELECT id_saison FROM saison WHERE annee=18),NULL,15,5,0,3,2,5,8,2,3,NULL,NULL,true,7);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='SCHIELE_LEO' AND licence='VT020067')),(SELECT id_saison FROM saison WHERE annee=18),NULL,13,5,1,1,3,2,2,1,2,NULL,NULL,true,8);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='BRENDLE_UGO' AND licence='VT020107')),(SELECT id_saison FROM saison WHERE annee=18),NULL,4,2,0,1,1,0,0,1,0,NULL,NULL,true,9);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='PREISS_GRUNENWALD_PIERRE' AND licence='VT010743')),(SELECT id_saison FROM saison WHERE annee=18),NULL,0,0,0,0,0,0,0,0,0,NULL,NULL,false,10);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='PLANA_RAFAEL' AND licence='VT020182')),(SELECT id_saison FROM saison WHERE annee=18),NULL,4,2,0,0,2,0,0,5,8,NULL,NULL,true,11);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='BURCKEL_LOUIS' AND licence='VT030314')),(SELECT id_saison FROM saison WHERE annee=18),NULL,6,3,0,1,2,0,2,4,5,NULL,NULL,false,13);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='OERTEL_THOMAS' AND licence='VT010025')),(SELECT id_saison FROM saison WHERE annee=18),NULL,8,4,0,0,4,0,2,2,1,NULL,NULL,true,5);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='KALTENBACH_THOMAS' AND licence='VT013217')),(SELECT id_saison FROM saison WHERE annee=18),NULL,10,3,0,0,3,4,10,3,6,NULL,NULL,true,6);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='KUHN_FLORIAN' AND licence='VT013213')),(SELECT id_saison FROM saison WHERE annee=18),NULL,5,2,0,0,2,1,2,1,0,NULL,NULL,false,7);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='GEIST_ALEXIS' AND licence='VT020701')),(SELECT id_saison FROM saison WHERE annee=18),NULL,0,0,0,0,0,0,0,4,0,NULL,NULL,true,8);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='REBHUN_FLORENT' AND licence='VT013231')),(SELECT id_saison FROM saison WHERE annee=18),NULL,21,7,3,0,4,4,8,2,4,NULL,NULL,false,9);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='DEL_PIN_JULES_VICTOR' AND licence='VT020796')),(SELECT id_saison FROM saison WHERE annee=18),NULL,8,3,0,0,3,2,2,1,2,NULL,NULL,true,10);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='HANS_QUENTIN' AND licence='VT013646')),(SELECT id_saison FROM saison WHERE annee=18),NULL,15,6,0,0,6,3,3,2,0,NULL,NULL,false,11);

INSERT INTO stats_joueurs (matchs_id,joueurs_id,saison_id,tdj,points,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,ecartplus,ecartmoins,5majeur,numero_joueur)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M' AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE (nom_joueur='SIGRIST_ANTHONY' AND licence='VT026086')),(SELECT id_saison FROM saison WHERE annee=18),NULL,13,6,1,0,5,0,0,1,0,NULL,NULL,true,12);


INSERT INTO stats_equipes (matchs_id,equipes_id,saison_id,ptsm,ptse,pts5,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,fautesprov)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18))),(SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))),(SELECT id_saison FROM saison WHERE annee=18),56,80,50,22,3,7,12,9,15,20,27,16);

INSERT INTO stats_equipes (matchs_id,equipes_id,saison_id,ptsm,ptse,pts5,tirs,trois,deuxext,deuxint,lfr,lft,fautes,lfc,fautesprov)
VALUES ((SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18))),(SELECT id_equipes FROM equipes WHERE (nom_equipe='DUTTLENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))),(SELECT id_saison FROM saison WHERE annee=18),80,56,39,31,4,0,27,14,27,16,15,20);

UPDATE stats_equipes SET age=15.125,antisportive=1,technique=0,disqualifiante=0 WHERE (matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18))) AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))));

UPDATE stats_equipes SET age=15.625,antisportive=0,technique=0,disqualifiante=0 WHERE (matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=002097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18))) AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='DUTTLENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))));


INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=2097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT020107' AND nom_joueur='BRENDLE_UGO'),(SELECT id_joueurs FROM joueurs WHERE licence='VT020046' AND nom_joueur='CHAMASSI_UGO'),(SELECT id_joueurs FROM joueurs WHERE licence='VT020182' AND nom_joueur='PLANA_RAFAEL'),(SELECT id_joueurs FROM joueurs WHERE licence='VT020067' AND nom_joueur='SCHIELE_LEO'),(SELECT id_joueurs FROM joueurs WHERE licence='VT010201' AND nom_joueur='STATH_THIBAUT'),NULL,56,80);
INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=2097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT020107' AND nom_joueur='BRENDLE_UGO'),(SELECT id_joueurs FROM joueurs WHERE licence='VT030314' AND nom_joueur='BURCKEL_LOUIS'),(SELECT id_joueurs FROM joueurs WHERE licence='VT020182' AND nom_joueur='PLANA_RAFAEL'),(SELECT id_joueurs FROM joueurs WHERE licence='VT010743' AND nom_joueur='PREISS_GRUNENWALD_PIERRE'),(SELECT id_joueurs FROM joueurs WHERE licence='VT020067' AND nom_joueur='SCHIELE_LEO'),NULL,0,0);
INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='ASL_DESSENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=2097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT020107' AND nom_joueur='BRENDLE_UGO'),(SELECT id_joueurs FROM joueurs WHERE licence='VT030314' AND nom_joueur='BURCKEL_LOUIS'),(SELECT id_joueurs FROM joueurs WHERE licence='VT020046' AND nom_joueur='CHAMASSI_UGO'),(SELECT id_joueurs FROM joueurs WHERE licence='VT010743' AND nom_joueur='PREISS_GRUNENWALD_PIERRE'),(SELECT id_joueurs FROM joueurs WHERE licence='VT020067' AND nom_joueur='SCHIELE_LEO'),NULL,0,0);
INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='DUTTLENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=2097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT020796' AND nom_joueur='DEL_PIN_JULES_VICTOR'),(SELECT id_joueurs FROM joueurs WHERE licence='VT020701' AND nom_joueur='GEIST_ALEXIS'),(SELECT id_joueurs FROM joueurs WHERE licence='VT013217' AND nom_joueur='KALTENBACH_THOMAS'),(SELECT id_joueurs FROM joueurs WHERE licence='VT010025' AND nom_joueur='OERTEL_THOMAS'),(SELECT id_joueurs FROM joueurs WHERE licence='VT026086' AND nom_joueur='SIGRIST_ANTHONY'),NULL,47,25);
INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='DUTTLENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=2097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT013646' AND nom_joueur='HANS_QUENTIN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT013217' AND nom_joueur='KALTENBACH_THOMAS'),(SELECT id_joueurs FROM joueurs WHERE licence='VT013213' AND nom_joueur='KUHN_FLORIAN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT013231' AND nom_joueur='REBHUN_FLORENT'),(SELECT id_joueurs FROM joueurs WHERE licence='VT026086' AND nom_joueur='SIGRIST_ANTHONY'),NULL,0,0);
INSERT INTO ecart_cinq (stats_equipes_id,joueur_1,joueur_2,joueur_3,joueur_4,joueur_5,tdj,ptsm,ptse) VALUES ((SELECT id_stats_equipes FROM stats_equipes WHERE equipes_id= (SELECT id_equipes FROM equipes WHERE (nom_equipe='DUTTLENHEIM' AND saison_id = (SELECT id_saison FROM saison WHERE annee=18) AND comite_id = (SELECT id_comite FROM comite WHERE nom_comite='LR02') AND competition_id = (SELECT id_competition FROM competition WHERE (chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt= 'U17M') AND poule_id=(SELECT id_poule FROM poule WHERE nom_poule='A'))))) AND matchs_id=(SELECT id_matchs FROM matchs INNER JOIN equipes ON id_equipes=equipedom_id INNER JOIN competition ON id_competition=competition_id WHERE (numero_match=2097 AND matchs.comite_id=(SELECT id_comite FROM comite WHERE nom_comite='LR02') AND chpt_id=(SELECT id_chpt FROM chpt WHERE nom_chpt='U17M') AND matchs.saison_id = (SELECT id_saison FROM saison WHERE annee=18)))),(SELECT id_joueurs FROM joueurs WHERE licence='VT020796' AND nom_joueur='DEL_PIN_JULES_VICTOR'),(SELECT id_joueurs FROM joueurs WHERE licence='VT013213' AND nom_joueur='KUHN_FLORIAN'),(SELECT id_joueurs FROM joueurs WHERE licence='VT010025' AND nom_joueur='OERTEL_THOMAS'),(SELECT id_joueurs FROM joueurs WHERE licence='VT013231' AND nom_joueur='REBHUN_FLORENT'),(SELECT id_joueurs FROM joueurs WHERE licence='VT026086' AND nom_joueur='SIGRIST_ANTHONY'),NULL,33,31);

